version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: ./nextjs/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    command: npm run dev

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - "9000:9000"
    command: >
      sh -c " 
        if [ ! -d vendor ]; then
          composer install;
        fi
      php-fpm "
    depends_on:
      - mysql
      - redis
    volumes:
      - public_data:/var/www/sns/php/public

  nodejs:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - redis

  redis:
    image: redis:6.0.16
    ports:
      - "16379:6379"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "10080:80"
    volumes:
      - public_data:/var/www/sns/php/public
    depends_on:
      - nextjs
      - php
      - nodejs

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    volumes:
      - ./mysql/data/:/var/lib/mysql
    env_file:
      - mysql-variables.env
    ports:
      - "13306:3306"

volumes:
  public_data:
    driver_opts:
      type: none
      device: ${PWD}/php/public
      o: bind
