version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "9000:9000"
    command: >
      sh -c " 
        if [ ! -d vendor ]; then
          composer install;
        fi
      php-fpm "
    depends_on:
      - mysql
      - redis
    volumes:
      - public_data:/var/www/sns/backend/public

  sse:
    build:
      context: .
      dockerfile: ./sse/Dockerfile
    ports:
      - "4001:4001"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - public_data:/var/www/sns/backend/public
    depends_on:
      - frontend
      - backend
      - sse

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    volumes:
      - ./mysql/data/:/var/lib/mysql
    env_file:
      - mysql-variables.env
    ports:
      - "3306:3306"

volumes:
  public_data:
